### ISSUE TITLE
"curl: option -LJ0 is unknown" error on fresh QSE

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.health#121]
Repo steps: 
  1. Downloaded a fresh QSE v4.2.0.0
  2. Download and extract the release zip (v0.1.zip)
  3. Ran `./gradlew build` from the root project directory. 

Received the following error: 

```
:analyze:vitals_ews:com.ibm.streamsx.health.analyze.rules.vitals.spl:build
:analyze:watsonexplorer:com.ibm.streamsx.health.analyze.watsonexplorer:getWEXToolkit
curl: option -LJO: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
:analyze:watsonexplorer:com.ibm.streamsx.health.analyze.watsonexplorer:getWEXToolkit FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/streamsadmin/health2/streamsx.health-0.1/analyze/watsonexplorer/com.ibm.streamsx.health.analyze.watsonexplorer/build.gradle' line: 23

* What went wrong:
Execution failed for task ':analyze:watsonexplorer:com.ibm.streamsx.health.analyze.watsonexplorer:getWEXToolkit'.
> Process 'command 'curl'' finished with non-zero exit value 2
```

FYI @chanskw @natashadsilva

**Comment by chanskw** [comment]
This seems like the curl install on the QSE is too old.  On the QSE, it has curl 7.19 and the options are not recognized.

On my own machine, I have curl 7.49 installed and the command works.  One work around is to update curl on the QSE.

**Comment by chanskw** [comment]
This needs to be fixed before Thursday.

**Comment by chanskw** [comment]
Fixed... use wget instead of curl
