### ISSUE TITLE
ADT and ORU parser running kill Streams console

### ISSUE THREAD

**Issue by swinkstn** [IBMStreams/streamsx.health#135]
Not long after running the ADT and ORU parsers the IBM Streams console fails.  The box link for the logs is here: https://app.box.com/s/rje3jivuoybb1gof8f6e9qq9ani6feer

**Comment by chanskw** [comment]
Is this still an issue?

**Comment by swinkstn** [comment]
Hey welcome back!  AFAIK yes but they were supposed to upgrade but I have not heard from them in a few weeks.  I will reach out. 
                                                Brandon Swink                        IT Architect & Technical Sales Specialist                        IBM Analytics                                                Phone: 720-395-1055                        E-mail: swink@us.ibm.com                                                                                Mailing Address:                        1000 BELLEVIEW ST                        Mail Drop 28-7035                        DALLAS TX 75215                                                
 
 
 
----- Original message -----From: Samantha Chan <notifications@github.com>To: "IBMStreams/streamsx.health" <streamsx.health@noreply.github.com>Cc: Brandon Swink <swink@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBMStreams/streamsx.health] ADT and ORU parser running kill Streams console (#135)Date: Tue, Sep 5, 2017 1:15 PM 
Is this still an issue?

**Comment by chanskw** [comment]
In our last discussion, this is no longer an issue.  Can I close?

**Comment by chanskw** [comment]
Last update I got is that everything seems ok... Please reopen if this is still an issue.
