### ISSUE TITLE
How do we compile HAPI microservice properly?

### ISSUE THREAD

**Issue by phcaptjim** [IBMStreams/streamsx.health#153]
Hi, I recently made a change to our HAPI code, specifically this file/location:
workspace_adt/com.ibm.streamsx.health.hapi/src/main/java/com/ibm/streamsx/health/hapi/mapper/AdtToModelMapper.java

Now I am wondering how to compile this properly?  My workspace_adt directory looks like this:
com.ibm.streamsx.health.hapi
com.ibm.streamsx.health.ingest
com.ibm.streamsx.health.spl
.gradle
streamsx.health
streamsx.health.tar

I am just unsure where to run the gradle build for my code to compile properly.  I have tried a few different places but it never seems to update properly.  I was not involved in the original build so I am unsure how this was done originally.

Any help would be great!  Thanks!

**Comment by chanskw** [comment]
Have you seen the instructions from here?
https://github.com/IBMStreams/streamsx.health/tree/develop/ingest/hl7

**Comment by phcaptjim** [comment]
Thanks for the link.  While that does provide some helpful information we are still unable to compile.  I am sure it's a simple issue but we will most likely need some assistance.  I can reach out to our IBM contact if you think that is best?

**Comment by phcaptjim** [comment]
We got some feedback and downloaded a fresh version of the toolkit and was able to compile.  Our issue was we moved our compiled code from Streams Studio (local) to our streams server.  We are in good shape now.  Thanks!

**Comment by natashadsilva** [comment]
@phcaptjim Glad to hear it's resolved.
