### ISSUE TITLE
healthdemo/ecg_streaming.py attempts to use a float as an int, which is not tolerated by later versions of Python or python packages

### ISSUE THREAD

**Issue by pcbye** [IBMStreams/streamsx.health#156]
When attempting to use a newer version of some python packages within Python 3.5, the following error occurs when running the healthcare demo sample:

healthdemo/ecg_streaming.py", line 39, in preprocess_MA_filtfilt
    tup['__algo_vars']['b'] = np.ones(tup['sampling_rate'] / 35.) / 35.
  File "/usr/IBM/anaconda3/lib/python3.5/site-packages/numpy/core/numeric.py", line 192, in ones
    a = empty(shape, dtype, order)
TypeError: 'float' object cannot be interpreted as an integer

It appears that this line is attempting to use the integer "divide" ( / ) operator on a float value, which seems to be tolerated by earlier versions of the package being used, but not later versions.  Suggestions found doing a search are that the code should use "//" instead of "/" as the divide operator.

**Comment by natashadsilva** [comment]
Fixed by PR #158

**Comment by pcbye** [comment]
Thank you.  Closing.
