### ISSUE TITLE
Initial Contribution Completion Checklist

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.health#27]
- [X] Testing of services - James
  - [X] Documentation - Samantha

@cancilla 
Please mark complete and give thumbs up if we are ready to go.

**Comment by cancilla** [comment]
I've tested and verified that the following services build and run successfully: 

 - com.ibm.streamsx.health.ingest.physionet.service.PhysionetIngestService
 - com.ibm.streamsx.health.hapi.services.OruR01Ingest
 - com.ibm.streamsx.health.analysis.ecg.service.RPeakDetectService
 - com.ibm.streamsx.health.beacon.ECGBeaconService

**Comment by chanskw** [comment]
@cancilla I tried running gradle build for physionet ingest service and RPeakDetect , but I don't seem to get an output directory with the service build content... can you please take a look?

Can you let me know where I should invoke the build from and where I should expect to see output.  I do see the output directory for the ECGBeaconService

**Comment by chanskw** [comment]
@cancilla I fixed the build scripts to include buildServivces target for both cases, can you please take a look and try this out.

**Comment by chanskw** [comment]
@cancilla and @petenicholls I have completed the documentation for the repository, please take a quick look at the write up and give +1 it looks good.  When that is done, we can declare victory.

**Comment by chanskw** [comment]
Closing.  All done!
