### ISSUE TITLE
Change "Real-time ECG Monitoring Sample" to "Real-time Healthcare Monitoring Sample"

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.health#29]
In the README.md in the repository root, there is a section entitled "Real-time ECG Monitoring Sample". The sample actually demonstrates monitoring of more than just ECG waveforms. I recommend that all references to "ECG Monitoring" be replaced with "Healthcare Monitoring".

**Comment by chanskw** [comment]
+1 sure
