### ISSUE TITLE
Support ingest from ViNES

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/streamsx.health#30]
[ViNES(R)](http://www.trueprocess.com/vines-medical-device-connectivity/)  from [True Process](http://www.trueprocess.com/) is a scalable, vendor-neutral platform for acquiring, sharing, and storing high-resolution data from biomedical devices.  

Add ViNES to the ingest service framework as described [here](https://github.com/IBMStreams/streamsx.health/wiki/Ingest-Service-Framework).

**Comment by chanskw** [comment]
Thanks for the contribution.  Marking this as done.
