### ISSUE TITLE
Define nomenclature for use in Observation model

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.health#41]
Fields such as Reading.readingType and Reading.uom will generally be populated with the same subset of values. 

Take for example he Reading.readingType attribute, which describes the type of reading that was observed. One of the challenges we have is that different ingest services are free to different spellings to specify the same reading type. For example, you may get "ECG Lead I", "ecg_lead_I", "lead I", etc.

We should adopt a standard nomenclature for the Streams Healthcare Analytic Platform to be used when specifying the values for these types. Analytic applications will likely rely on the value set by this attribute to determine the type of analysis to run. Likewise, visualization applications may use this value to generate the graphs. In short, this will help to promote interoperability between services and applications. 

We can start by looking at ISO 11073 and PCD Profile Rosetta Terminology Mapping for guidance on how to define this nomenclature. 

https://en.wikipedia.org/wiki/ISO/IEEE_11073
http://wiki.ihe.net/index.php/PCD_Profile_Rosetta_Terminology_Mapping

**Comment by chanskw** [comment]
I think we should also look at this:
https://www.nlm.nih.gov/healthit/snomedct/

I believe this is the most widely used and comprehensive standard.

I can't find the details of this yet, but what about this for Unit of measure?
https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/NCI_UCUM/

**Comment by chanskw** [comment]
For observation type, we should also consider LOINC code as defined by FHIR:
https://www.hl7.org/FHIR/DSTU1/valueset-observation-codes.html

**Comment by chanskw** [comment]
FHIR recommends this for UOM:  UCUM -  http://unitsofmeasure.org/ucum.html
