### ISSUE TITLE
JSON Decode error - 2nd cell on Phython notebook demo

### ISSUE THREAD

**Issue by bradersk** [IBMStreams/streamsx.health#43]
Hello, I get the following error message when I try to run the 2nd cell on the HealthcareDemo-AnalyticsService demo:

/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py in raw_decode(self, s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
/home/streamsadmin/.local/lib/python3.5/site-packages/streamsx/rest.py in get_vcap_services(config)
    183             try:
--> 184                 with open(vs) as vcap_json_data:
    185                     vs = json.load(vcap_json_data)

FileNotFoundError: [Errno 2] No such file or directory: 'vcap_services.json'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-852159a6ee05> in <module>()
     51 
     52 # Retrieve view for a patient
---> 53 patient_view = getPatientView(3)
     54 
     55 print('DONE')

<ipython-input-2-852159a6ee05> in getPatientView(patient_id)
     47     patient_view = patient_data.view()
     48 
---> 49     submit('ANALYTICS_SERVICE', topo, config)
     50     return patient_view
     51 

/home/streamsadmin/.local/lib/python3.5/site-packages/streamsx/topology/context.py in submit(ctxtype, graph, config, username, password, log_level)
     75     """    
     76     logger.setLevel(log_level)
---> 77     context_submitter = _SubmitContextFactory(graph, config, username, password).get_submit_context(ctxtype)
     78     try:
     79         return context_submitter.submit()

/home/streamsadmin/.local/lib/python3.5/site-packages/streamsx/topology/context.py in get_submit_context(self, ctxtype)
    378             if not (sys.version_info.major == 3 and sys.version_info.minor == 5):
    379                 raise RuntimeError("The ANALYTICS_SERVICE context only supports Python version 3.5")
--> 380             return _RemoteBuildSubmitter(ctxtype, self.config, self.app_topology)
    381         else:
    382             logger.debug("Using the BaseSubmitter, and passing the context type through to java.")

/home/streamsadmin/.local/lib/python3.5/site-packages/streamsx/topology/context.py in __init__(self, ctxtype, config, app_topology)
    271         super(_RemoteBuildSubmitter, self).__init__(ctxtype, config, app_topology)
    272 
--> 273         self._set_vcap()
    274         self._set_credentials()
    275 

/home/streamsadmin/.local/lib/python3.5/site-packages/streamsx/topology/context.py in _set_vcap(self)
    302     def _set_vcap(self):
    303         "Set self.vcap to the VCAP services, from env var or the config"
--> 304         self._vcap = VcapUtils.get_vcap_services(self._config())
    305 
    306     def _set_credentials(self):

/home/streamsadmin/.local/lib/python3.5/site-packages/streamsx/rest.py in get_vcap_services(config)
    185                     vs = json.load(vcap_json_data)
    186             except:
--> 187                 raise ValueError("VCAP_SERVICES information is not JSON or a file containing JSON:", vs)
    188         return vs
    189 

ValueError: ('VCAP_SERVICES information is not JSON or a file containing JSON:', 'vcap_services.json')

Please advise.

Many thanks, Sarah

**Comment by chanskw** [comment]
Hi Sarah,


The healthcare analytics service demo is experimental, and not quite ready yet.  It requires the use  of Streaming Analytics Bluemix service.

Can you please try to run the HealthcareDemo-Distributed.ipynb notebook instead and let me know if that works for you?

Thanks!
Samantha

**Comment by chanskw** [comment]
We have updated the sample, so that it makes it clear that the analytics service notebook is experimental avoid further confusion.  You may want to pull the changes in and try again.  Please let me know if it still does not work and I am glad to help.

**Comment by chanskw** [comment]
I have rerun the sample and I believe this is fixed.  Please reopen if this is still an issue for you.
Thanks!
