### ISSUE TITLE
Versioning the platform

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.health#49]
As we are now following the Hubflow process for contributing code, we should consider adding a version number to the platform. This will allow us to generate releases with appropriate tags and keep track of what features were added to which release.

**Comment by chanskw** [comment]
I think the top level platform should have a version number.
Each of its subcomponents will have its own version number.
I think it will be useful to have a tool that can collect all version and component info from the platform, so this informaation can be displayed.

**Comment by chanskw** [comment]
Added top level info.xml to start versioning the platform.
