### ISSUE TITLE
HL7: Extract Additional Value Requirements

### ISSUE THREAD

**Issue by swinkstn** [IBMStreams/streamsx.health#5]
We need to extract the PV1 PL (3), MSH 3, and  MSH 4 in to the output tuple.

**Comment by chanskw** [comment]
This is what these fields mean:
MSH3 - Sending Application
MSH4 - Sending Facility
PV1-3: Assigned Patient Location (PL)

**Comment by chanskw** [comment]
@swinkstn are you sure we need PV1-3 for assigned patient location?  That information is already extracted and they are put in the "location" attribute of the tuple.  Is that field empty for you for some reason?

**Comment by swinkstn** [comment]
Ugh!  Sorry!  If those are being extracted already then that is fine sorry for the confusion.  Please test with the samples I sent you from the customer to be sure that field is coming out.

**Comment by chanskw** [comment]
I think the problem is that location is always empty with the latest set of sample data.
I have adjusted the code to extract out the info correctly.

**Comment by chanskw** [comment]
Fixed issue, please try again.  I added two fields:  sendingApp and sendingFacility into the SPL tuple.
