### ISSUE TITLE
EWSService does not handle resp rate from beacon

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.health#65]
The resp rate always seems to be zero.  The EWS service does not work as a result.

**Comment by chanskw** [comment]
... we do get the values, but it's not in expected unit of measure

**Comment by chanskw** [comment]
@cancilla what is the uom of the resp rate from the beacon service? 
The normal RESP rate is 12-15 breaths per minute.  But the values that we are getting is -1.0 to 1.0.

**Comment by cancilla** [comment]
@chanskw Good catch! I'm not really sure why the values were between -1.0 and 1.0. It may have been a different type of RESP measurement being used. I have updated the RESP data coming from the beacon service to be more consistent with what you expect to see.

**Comment by chanskw** [comment]
Thanks!  Verified fixed
