### ISSUE TITLE
Repository reorganization to better fit microservice framework design

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.health#7]
We have recently published a roadmap for the Streams Healthcare Analytics Platform.  You can find the roadmap here:

[Roadmap](https://github.com/IBMStreams/streamsx.health/wiki/Streams-Healthcare-Analytics-Platform-Roadmap)

The platform is currently designed to use a micrservice architecture, which can contain multiple toolkits applications that can be assembled together to form an application.

The repository needs to be reorganized to better facilitate the development of this platform.

**Comment by chanskw** [comment]
We are going to create top level directories based on the main components of the platform.  Initially, we are going to have the follow components:

* ingest
* analyze
* simulate
* samples

For ingest where we are going to to have multiple projects, we suggest the following:

* ingest
    * common
    * physionet
    * hl7

Future contribution will have its own directory.

For other components, we will leave it as a flat directory structure for now, until we have more contributions and a better feeling on how we should organize the services.

**Comment by cancilla** [comment]
+1

**Comment by chanskw** [comment]
@cancilla I have pushed the reorg to master, can you please check it out.

**Comment by chanskw** [comment]
Fixed, open new issue if you have any comment please.
